### ISSUE TITLE
miss-spelling of minimumLineSpacing?

### ISSUE THREAD

**Issue by wakaryry** [czl0325/ZLCollectionView#1]
Seems in line 360 -370:
```swift
CGPoint leftPt = CGPointMake(attributes.frame.origin.x - minimumLineSpacing, attributes.frame.origin.y);
```

I do not dive into logic. 
It's not miss-spelling？

minimunItemSpacing?

**Comment by czl0325** [comment]
Yes,  I made a mistake, minimumInteritemSpacing is right.
