### ISSUE TITLE
PercentLayout设置百分比布局 数据源不足时宽度不对

### ISSUE THREAD

**Issue by focus-ming** [czl0325/ZLCollectionView#11]
当我设置PercentLayout布局时候
在percentOfRow 中 我设置了section == 1 时候返回 1.0/5 
section == 1 边距设置的方法 insetForSectionAtIndex 设置为 UIEdgeInsetsMake(0, 23, 0, 23);
列间距 minimumInteritemSpacingForSectionAtIndex section == 1时候 设置为24；
那么按照我的理解section == 1 时候 没个cell的宽度应该为 
CGFloat w = (SCREENWIDTH - 24*4-23*2)/5;
但是我发现 当我的数据源为5时候 w确实没有问题  但是当数据源不够五个时 这个宽系统计算是错误。
求大神能帮忙解决一下。项目马上提交了 碰到这个问题 很急，在线等。谢谢了先

**Comment by czl0325** [comment]
急的话先用FillLayout替代，百分比布局我要重写

**Comment by czl0325** [comment]
0.8.7修改好这个问题

**Comment by focus-ming** [comment]
> 急的话先用FillLayout替代，百分比布局我要重写

好的 感谢 辛苦

**Comment by focus-ming** [comment]
> 0.8.7修改好这个问题

今天看到更新到了0.8.7 
出现了bug
我的UI页面 总共4行 第一行 与第4行 有组头 
Bug 表现为 第一行第二行第三行 frame的Y都为0 摞在一起 （这三行目前目前都只有一个cell）第四行是正常的在第三行下面正常显示。

**Comment by czl0325** [comment]
什么布局？方便贴上代码吗？

**Comment by focus-ming** [comment]
代码有点多 我把那个页面抽离了出来 写了个demo 我邮箱812017040@qq.com 你联系我一下 我发你demo

**Comment by focus-ming** [comment]
> 什么布局？方便贴上代码吗？

代码有点多 我把那个页面抽离了出来 写了个demo 我邮箱812017040@qq.com 你联系我一下 我发你demo

**Comment by czl0325** [comment]
295183917@qq.com
