### ISSUE TITLE
minimumLineSpacingForSectionAtIndex 在不同布局下规则不一致

### ISSUE THREAD

**Issue by focus-ming** [czl0325/ZLCollectionView#12]
minimumLineSpacingForSectionAtIndex 设置为10
目前一个页面不同section 采用的是PercentLayout 与ClosedLayout两种方式混合排序。当设置了行间距的时候发现 在PercentLayout的样式下 系统默认在第一行上方加入一个 行间距。  但是在ClosedLayout 样式下是在最后一行下方加入一个行间距。 这导致了 当这两个样式交界处的时候 间隙无法去调整的问题。不知道能否改成minimumLineSpacingForSectionAtIndex 既不在最上面也不在最下面添加间距 只设置行与行之间的间距 最上面下面的间距统一交给insetForSectionAtIndex来处理

**Comment by czl0325** [comment]
0.8.7修改好这个问题

**Comment by focus-ming** [comment]
> 0.8.7修改好这个问题

感谢
