### ISSUE TITLE
现在可以支持Swift了吗

### ISSUE THREAD

**Issue by willokyes** [czl0325/ZLCollectionView#15]
在Swift项目中使用了下，发现不行，是我操作不对，还是此库本身不支持Swift？

ps：按理说，桥接一下，应该不会有问题的。

还请指教！

**Comment by czl0325** [comment]
没试过在swift下调用，是报什么错误呢？

**Comment by willokyes** [comment]
你的OC代码不会调用Swift类里实现的UICollectionViewDelegateFlowLayout代理的方法。
已找到解决方法。
测试通过。
