### ISSUE TITLE
感谢分享！(可以实现 section 1 横行滑动；section 2 纵向滑动 吗？如下图)

### ISSUE THREAD

**Issue by MZC0829** [czl0325/ZLCollectionView#24]
![image](https://user-images.githubusercontent.com/18035492/70767279-9a0e8280-1d9b-11ea-93bc-2503a4480e5b.png)

**Comment by czl0325** [comment]
你有没有实现思路？

**Comment by xiaohangfamily** [comment]
不同方向滚动只能靠多个scrollview了吧。。

**Comment by 986138497** [comment]
可以用 tableview,然后上面用 cell, 里面放 collectionview

**Comment by wangwanjie** [comment]
这有关联吗？cell 里面 套一个 UICollectionView 就行啊，你这是定高的，处理很简单
