### ISSUE TITLE
   [self.collectionView reloadItemsAtIndexPaths:@[index]]; 直接闪退

### ISSUE THREAD

**Issue by LoSenTrad** [czl0325/ZLCollectionView#35]
[self.collectionView reloadItemsAtIndexPaths:@[index]];

reload items直接闪退

**Comment by czl0325** [comment]
你用法有问题吧？？

[weakSelf.collectionViewLabel reloadItemsAtIndexPaths:@[[NSIndexPath indexPathForItem:0 inSection:0]]];

**Comment by LoSenTrad** [comment]
刷新item 或者整个表刷新 都有异常

**Comment by czl0325** [comment]
什么异常呢？我在我demo里测试没问题啊，我demo有带下拉刷新

**Comment by LoSenTrad** [comment]
我做单页瀑布流, reloadData 到时候 第一个item 一直在闪

**Comment by LoSenTrad** [comment]
第二次reloadData的时候

**Comment by czl0325** [comment]
你发个demo到我邮箱下。295183917@qq.com

**Comment by LoSenTrad** [comment]
好的 有时间 我整理一个demo出来
