### ISSUE TITLE
cell高度自适应出现问题

### ISSUE THREAD

**Issue by xiaoyao20084321** [czl0325/ZLCollectionView#36]
![image](https://user-images.githubusercontent.com/10344550/99764780-c056a980-2b38-11eb-94c4-d109391cb67d.png)
如图，直接下载的demo运行的，就看见问题

**Comment by Wuou** [comment]
[UIScreen mainScreen].bounds.size.width / 2.0 - 30   改成 ([UIScreen mainScreen].bounds.size.width - 30) / 2.0

**Comment by xiaoyao20084321** [comment]
> [UIScreen mainScreen].bounds.size.width / 2.0 - 30 改成 ([UIScreen mainScreen].bounds.size.width - 30) / 2.0

对哦， 应该先减去30在除以2的，老哥多谢
