### ISSUE TITLE
有个小小的建议

### ISSUE THREAD

**Issue by honeybeeSwinging** [czl0325/ZLCollectionView#4]
首先对大哥贡献出这不错的项目表示感谢和赞赏！不过有个小小的建议能否提一下，不知道大哥平时写代码是这样子，还是因为这个是github项目这样子，就是我们都很希望你加入一点代码注释，最好是越详细越好！辛苦了

**Comment by czl0325** [comment]
平时写代码都基本不写注释的，这个还是因为开源库的原因在头文件写了注释了。
