### ISSUE TITLE
请问怎么实现 整体垂直,分区水平滚动效果?

### ISSUE THREAD

**Issue by axinger** [czl0325/ZLCollectionView#40]
怎么实现这个功能
有2行,每行是左右滑动的
<img width="500" alt="图片" src="https://user-images.githubusercontent.com/18339649/117606990-a0ba4880-b18d-11eb-9492-bb96af639fb0.png">

**Comment by czl0325** [comment]
纵向uicollectionview的cell是横向的uicollectionview
