### ISSUE TITLE
支持横行cell的宽度，高度自适应吗？

### ISSUE THREAD

**Issue by Wuou** [czl0325/ZLCollectionView#41]
支持横行cell的宽度，高度自适应吗？

**Comment by czl0325** [comment]
宽高自适应是使用第三方库（UICollectionView+ARDynamicHeightLayoutCell）实现的。他提供的方法只有固定宽度计算高度或者固定高度计算宽度，想要宽高都自适应，需要自己计算出宽度和高度传到collectionviewcell的代理里面。

**Comment by Wuou** [comment]
👌明白了
