### ISSUE TITLE
针对瀑布流的疑问

### ISSUE THREAD

**Issue by ke112** [czl0325/ZLCollectionView#43]
如果要用瀑布流 ,UICollectionView+ARDynamicHeightLayoutCell  是必须要用的吗 请问,那为什么不把这个文件 也放到pod的库里?

**Comment by czl0325** [comment]
UICollectionView+ARDynamicHeightLayoutCell  这个不是我写的，是用github别人开源的第三方库，当然你也可以不用他，还有其他更好的方法也可以

**Comment by ke112** [comment]
感谢回复,你好,如果不用那个库 ,对于使用瀑布流的时候 ClosedLayout,怎么高度自适应?     
sizeForItemAtIndexPath这个方法 怎么返回 ? 我不想根据 数据算 在model里写一个cellHeight的属性,我也想根据设置的约束,自动布局,您这个库 支持吗?

**Comment by czl0325** [comment]
你尝试下uicollectionviewcell的自动高度试试。我也没尝试过。你看看普通的uicollectionviewflowlayout是怎么实现自动高度的，那我的也是一样的方法
