### ISSUE TITLE
您好，可以实现某个分区的所有cell有一个统一的边框或者圆角+阴影嘛

### ISSUE THREAD

**Issue by xiaoyao20084321** [czl0325/ZLCollectionView#45]
您好，可以实现某个分区的所有cell有一个统一的边框或者圆角+阴影嘛，如下图
![1624501633159](https://user-images.githubusercontent.com/10344550/123193436-660b3600-d4d7-11eb-8002-9b3ab67c1b4b.jpg)

**Comment by czl0325** [comment]
这个你自定义背景view，画出背景的白色view，然后uicollectionviewcell根据背景的白色view用insetForSectionAtIndex来做偏移

**Comment by xiaoyao20084321** [comment]
太麻烦了，主要是你看section还有一个渐变色的背景图片，我后来用tableView+collectionView来实现了，

**Comment by czl0325** [comment]
不麻烦吧，不就是自定义一个view，设置下背景渐变色，还有白色的图片吧

**Comment by xiaoyao20084321** [comment]
哦哦，我想错了， 我想着这有一个背景view和一个背景图片，但是咱们的第三方库只支持返回一个view，所以才不好做， 我可以把图片添加到自定义的view上，然后在把view  return过去
