### ISSUE TITLE
横向collectionView， ColumnLayout布局时候，Item能否横向顺序排列

### ISSUE THREAD

**Issue by xiaoyao20084321** [czl0325/ZLCollectionView#47]
现在您这边Dmeo里面实现的是
![image](https://user-images.githubusercontent.com/10344550/128300203-12ea1830-3da9-4685-83fb-923d1f882bff.png)
，能否实现
![image](https://user-images.githubusercontent.com/10344550/128300330-fa0f0af9-3f10-4b4c-8524-addb1d29ce78.png)
这种效果

**Comment by souls-shaohui** [comment]
大佬，麻烦这个问题解决了吗？怎么使用呢？

**Comment by xiaoyao20084321** [comment]
我已经忘了我当时怎么解决的了。。。

**Comment by xiaoyao20084321** [comment]
貌似最后没实现

**Comment by xiaoyao20084321** [comment]
> 大佬，麻烦这个问题解决了吗？怎么使用呢？

我已经忘了当时怎么解决的了， 貌似最后没实现
