### ISSUE TITLE
使用 NSLayoutConstraint 进行header拉伸的时候会崩溃

### ISSUE THREAD

**Issue by mayunhao910324** [czl0325/ZLCollectionView#49]
将header 中的 imageview 跟viewcontroller 中的view 进行绑定会崩溃

 NSLayoutConstraint *layout = [self.backImage.topAnchor constraintEqualToAnchor:collectionView.topAnchor];
 [NSLayoutConstraint activateConstraints:@[layout]];

但是使用普通的UICollectionViewFlowLayout 却没有问题

错误信息：

Terminating app due to uncaught exception 'NSGenericException', reason: 'Unable to activate constraint with anchors <NSLayoutYAxisAnchor:0x2814699c0 "UIImageView:0x10ac6f2a0.top"> and <NSLayoutYAxisAnchor:0x28144ad00 "UICollectionView:0x10c176c00.top"> because they have no common ancestor.  Does the constraint or its anchors reference items in different view hierarchies?  That's illegal.'

**Comment by czl0325** [comment]
绑定错了吧。你怎么会backImage和collectionView绑定呢？backImage的父容器是header不是collectionView把

**Comment by mayunhao910324** [comment]
虽说两个父视图不一样 但是普通的layout 就没问题 很诧异
