### ISSUE TITLE
横向collectionView， ColumnLayout布局时候，Item能否横向顺序排列 

### ISSUE THREAD

**Issue by souls-shaohui** [czl0325/ZLCollectionView#53]
能否按照这样排列
1   2  3
4  5  6
而非
1   4
2   5
3   6

**Comment by czl0325** [comment]
这个问题之前有说过了，不可能的，横向的宽度是无穷大的，我怎么可能知道你要在什么时候换行呢？
你要实现这个功能，只能一个横向的collectionview，每一页都是一个纵向的collectionview
