### ISSUE TITLE
ios 15会闪退

### ISSUE THREAD

**Issue by 18621504096** [czl0325/ZLCollectionView#54]
在ios15以下可以正常工作但是ios15会闪退报错
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'UICollectionView (<UICollectionView 0x14433f000>) is stuck in its update/layout loop. This can happen for many reasons, including self-sizing views whose preferred attributes are not returning a consistent size. To debug this issue, check the Console app for logs in the "UICollectionViewRecursion" category.'
不知道是什么原因

**Comment by 18621504096** [comment]
[super invalidateLayoutWithContext:context];

**Comment by czl0325** [comment]
怎么会闪退呢？我在模拟器上测试15.5都运行正常，你用我的demo会闪退吗

**Comment by czl0325** [comment]
再试看看

**Comment by czl0325** [comment]
更新1.4.6

**Comment by 18621504096** [comment]
因为一直没找到问题用别的第三方先替代了一下，最近找到了这个问题好像是因为我用了预估高度导致的，在ios15以下都可以的ios15以上的就会报错
 layout.estimatedItemSize

**Comment by 18621504096** [comment]
把这一行注释掉就可以了
