### ISSUE TITLE
iOS15.5崩溃，列表不停地移除数据，请求数据会崩溃

### ISSUE THREAD

**Issue by tang786472181** [czl0325/ZLCollectionView#56]
"request for layout attributes for decoration view of kind ZLCollectionReusableView in section 0 when there are only 0 sections in the collection view"

ZLCollectionViewBaseFlowLayout
#pragma mark - 所有cell和view的布局属性
- (NSArray *)layoutAttributesForElementsInRect:(CGRect)rect
{
    NSArray* superAttris = [super layoutAttributesForElementsInRect: rect];
    // 判断是否有数据源
    if (self.collectionView.numberOfSections == 0) {
        return superAttris;
    }

    // 原逻辑
    ....
    }
}

**Comment by czl0325** [comment]
已加入

**Comment by tang786472181** [comment]
谢谢
