### ISSUE TITLE
有关float的相等判断

### ISSUE THREAD

**Issue by SoloChow** [czl0325/ZLCollectionView#6]
有关float的相等判断，建议改用 exp (A - B) < 0.01或其它更准确的判断方式。因为精度问题，在判断上时常会导致布局错乱。

**Comment by czl0325** [comment]
是哪个布局需要加这个？

**Comment by SoloChow** [comment]
` attributes.frame = CGRectMake([xFill floatValue]==edgeInsets.left?[xFill floatValue]:[xFill floatValue]+minimumInteritemSpacing, [yFill floatValue]==maxYOfFill?[yFill floatValue]:[yFill floatValue]+minimumLineSpacing, self.isFloor?floor(itemSize.width):itemSize.width, itemSize.height);`

**Comment by czl0325** [comment]
奇怪，我是向下取整了，照理应该不会出现问题才对，顶多就是重新换行而已啊。

**Comment by SoloChow** [comment]
你的宽度向下取整了，但是高度没有，所以也会引起这个问题。

**Comment by czl0325** [comment]
已修改好
