### ISSUE TITLE
更新了1.4.7之后，在瀑布流布局会有cell布局的残影。

### ISSUE THREAD

**Issue by lrsalway-here** [czl0325/ZLCollectionView#62]
更新了1.4.7之后，在瀑布流布局会有cell布局移动的“残影”问题。肉眼可见由上往下的移动轨迹，可能更新布局的相关代码存在一些问题，在1.4.5版本上是不会的。1.4.7版本 真机、模拟器都试过了，都有问题。

注: 
     使用的是- (void)insertItemsAtIndexPaths:(NSArray<NSIndexPath *> *)indexPaths;进行刷新。使用- (void)reloadData; 方法也会有较明显的闪动。
 
![图片](https://user-images.githubusercontent.com/18479815/202116078-3db555c4-6638-463d-a9bd-cfb5d2b509e2.png)

![图片](https://user-images.githubusercontent.com/18479815/202116378-399fa544-09f4-4acc-b60c-91e63091678d.png)

**Comment by czl0325** [comment]
你的瀑布流的cell高度怎么设置的？可否提供一个demo？

**Comment by czl0325** [comment]
可能是你不是在主线程里执行ui操作
