### ISSUE TITLE
在 swift 使用 ZLCollectionViewVerticalLayout 这个的填充 FillLayout 布局 布局错误

### ISSUE THREAD

**Issue by summerxx27** [czl0325/ZLCollectionView#65]
在 reloadData 后就会布局错误
如图 https://p.ipic.vip/ad1rkq.jpg

reloadData后, ZLCollectionViewVerticalLayout 这个文件中
 if (!self.isNeedReCalculateAllLayout) {
        return;    } 这里会直接 return

**Comment by summerxx27** [comment]
写了个demo 你有空的时候看看哈 运行点击第十行 cell 代码在这里 CollectionViewLayoutDemoViewController里面

https://github.com/summerxx27/XTAnimations

**Comment by czl0325** [comment]
我运行你的demo没发现问题。

**Comment by czl0325** [comment]
<img width="344" alt="image" src="https://user-images.githubusercontent.com/2100549/228470792-105ce53c-a3a1-4aa0-81e9-c86a62815ead.png">

**Comment by summerxx27** [comment]
噢噢 我的 demo reloaddata, 做了DispatchQueue.main.async执行,  去掉就会有问题了.
| |
summerx
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年03月29日 16:16 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [czl0325/ZLCollectionView] 在 swift 使用 ZLCollectionViewVerticalLayout 这个的填充 FillLayout 布局 布局错误 (Issue #65) |

我运行你的demo没发现问题。
