### ISSUE TITLE
列布局 ColumnLayout， 纵向 item 排列问题

### ISSUE THREAD

**Issue by linwear** [czl0325/ZLCollectionView#66]
ColumnLayout 列布局，2 列，比如有3个item @[A, B, C]，其中A 高度 100、B 高度 90、C 高度 80
这时它们显示顺序并不是
A  B
C   ·
而是
A  B
  ·   C
也就是说 item并不与数据源顺序一致，而是取决于那一列的高度最小就拼在谁后面，数据一多看起来就像数据乱了，无法按正常预期排列

这能改下么？ @czl0325

**Comment by linwear** [comment]
![WX20230322-093211@2x](https://user-images.githubusercontent.com/121668936/226778793-4c3eeb71-a3cc-4099-89ff-234ee07eef35.png)

**Comment by linwear** [comment]
![WX20230322-102809@2x](https://user-images.githubusercontent.com/121668936/226786258-9dedc216-b54c-4928-95fc-831003bde858.png)
@czl0325

**Comment by linwear** [comment]
![1679454819620](https://user-images.githubusercontent.com/121668936/226792768-7b358fb9-a007-4ae1-892f-3b91f1fec482.jpg)
给你参考，改这么几行代码是可行的。为了有更好的体验，满足更多的业务需求，可以在公开的.h文件，增加个属性 or 委托代理方法，表示瀑布流的排列方式，这样既可以保留你原有的排列方式，也可以满足需要排序的业务需求

**Comment by linwear** [comment]
![WX20230322-115233@2x](https://user-images.githubusercontent.com/121668936/226797802-7dc9631a-5695-4555-99ba-e89c7243871e.png)
Done!

**Comment by czl0325** [comment]
1.4.9版本已经增加瀑布流排序方式的字段，感谢

**Comment by wsrGitHub** [comment]
> 1.4.9版本已经增加瀑布流排序方式的字段，感谢

我可以更新了
