### ISSUE TITLE
填充式布局，存在严重的性能问题。

### ISSUE THREAD

**Issue by zhenxinguazi** [czl0325/ZLCollectionView#68]
填充式布局，采用多层for循环嵌套计算x、y值，当数据量比较大的时候，刷新一次布局嵌套的for循环高达几十万上百万次计算。刷新一次要三秒以上才能完成。

**Comment by czl0325** [comment]
数据量多大？一般不都是分页吗？

**Comment by czl0325** [comment]
我觉得计算布局x,y耗时是忽略不计的吧，现在cpu都很强，就让cpu运算100万个x,y也是微秒级别的事情，你耗时是耗时在渲染吧，渲染几百万个视图才是耗时。
