### ISSUE TITLE
文字太多就乱套了，是我用的不对吗 ，急急急 求作者大哥解答

### ISSUE THREAD

**Issue by zhanglongjiang** [czl0325/ZLCollectionView#75]
![IMG_1252](https://github.com/user-attachments/assets/8ecebfc0-3a94-42cc-9084-aa9a4ce91c46)
![IMG_1253](https://github.com/user-attachments/assets/2cd6834d-5762-4864-b7aa-9a647cbe3017)
![IMG_1254](https://github.com/user-attachments/assets/75e80ebd-d306-4366-9750-687af9652f7a)
![IMG_1256](https://github.com/user-attachments/assets/5302d940-3183-4ad8-a4d4-5e29dc4f2b51)

**Comment by zhanglongjiang** [comment]
_titleLabel.numberOfLines = 0;
最带宽度那就是屏幕宽度了

**Comment by zhanglongjiang** [comment]
用的 LabelLayout

**Comment by zhanglongjiang** [comment]
用的 LabelLayout,如果文字过多需要全都显示，

**Comment by czl0325** [comment]
labellayout只适用于单行文字，且你需要计算出文字的宽度来设置itemSize。如果你是多行文字，你可以尝试用fillLayout。同样需要设置itemSize
