### ISSUE TITLE
作者,您好,是否小尺寸的机型使用填充式布局会有问题想请教一下

### ISSUE THREAD

**Issue by XcodePlayer** [czl0325/ZLCollectionView#76]
![image](https://github.com/user-attachments/assets/a0b87061-ffca-49f9-964f-ea6f48e621ea)
上面的是用iPhoneSE机型做出来的效果图
![image](https://github.com/user-attachments/assets/d01202b2-cfc2-486a-bd7d-6dddeeb72e5c)
下面的是iPhoneX的
这indexpath错乱是否与屏幕尺寸有关

**Comment by czl0325** [comment]
感觉是你1和2的高度设置不对。如果0的高度是100。1和2应该是(100-空隙)/2。SE仔细看2的底部比0的底部略高，导致3排到2的下面去了

**Comment by czl0325** [comment]
你先试试1,2的高度为整数的情况看看

**Comment by XcodePlayer** [comment]
试了下确实是高度的问题,已经解决,十分感谢您的回复
