### ISSUE TITLE
对section背景进行一些操作的代理方法.... loadView，怎么用？

### ISSUE THREAD

**Issue by willokyes** [czl0325/ZLCollectionView#8]
这个库用起来很好，有个小疑问，

//对section背景进行一些操作
- (void)collectionView:(UICollectionView *)collectionView layout:(ZLCollectionViewFlowLayout *)collectionViewLayout loadView:(NSInteger)section {
    //NSLog(@"当前section=%zd，需要处理什么操作？",section);
}

这个代理方法究竟有何用处？

在这个方法里没法获取到背景视图？

没找到相关的获取背景视图接口。

还请指教，谢谢~

**Comment by willokyes** [comment]
如果能获取到section背景视图，那就可以根据条件给背景视图里的imageView设置不同的图片了。
在上面代理方法里，如何获取到section背景视图，还请指教

**Comment by czl0325** [comment]
从上面代理方法不是可以取到你是当前第几个section的自定义背景view吗？你实现把每个背景view保存成一个数组，从数据取出第section个对象，就是你的view对象，再调用view对象的方法。如设置图片

**Comment by willokyes** [comment]
@czl0325 谢谢您，您的库很好用，简直是量身定制。如果类里面提供有自定义section背景view的数组，就更好了，嘻嘻 ^_^ ^_^

**Comment by willokyes** [comment]
大神，真的不知如何获取装饰视图即section背影视图的方式，望稍详细些，或您更新下代码提供个接口方法，麻烦了

**Comment by focus-ming** [comment]
在你的demo中(void)collectionView:(UICollectionView *)collectionView layout:(ZLCollectionViewFlowLayout *)collectionViewLayout loadView:(NSInteger)section {
//NSLog(@"当前section=%zd，需要处理什么操作？",section);
}
放开注释
demo中section总数是10 按我的理解应该从输出从0 到 9的 
但是实际情况是 section= 0 section= 4 成对 重复打印。不是很明白这个代理方法到底该怎么用？

希望能得到大神解答！

**Comment by focus-ming** [comment]
> 从上面代理方法不是可以取到你是当前第几个section的自定义背景view吗？你实现把每个背景view保存成一个数组，从数据取出第section个对象，就是你的view对象，再调用view对象的方法。如设置图片

在你的demo中(void)collectionView:(UICollectionView *)collectionView layout:(ZLCollectionViewFlowLayout *)collectionViewLayout loadView:(NSInteger)section {
//NSLog(@"当前section=%zd，需要处理什么操作？",section);
}
放开注释
demo中section总数是10 按我的理解应该从输出从0 到 9的 
但是实际情况是 section= 0 section= 4 成对 重复打印。不是很明白这个代理方法到底该怎么用？

希望能得到大神解答！

**Comment by czl0325** [comment]
这个代理暂时不要用了，会反复调用。
如果把shouldInvalidateLayoutForBoundsChange设置成NO，就可以只调用一次，但是布局又会出现问题，还没找出原因

**Comment by czl0325** [comment]
改了一下，方法不会持续调用了，但是经测试该方法无效。不要用这方法了

**Comment by czl0325** [comment]
有曲线救国的方法，用绝对定位吧，把第0个元素设置成背景，第1个开始每个元素都盖在背景上，让他们的z序大于背景

**Comment by czl0325** [comment]
其实在后面的时候想在自定义背景view里面执行一些操作，还是有很多办法的，比如说定义个通知
